### PR TITLE
Refactor login flow

### PR DESCRIPTION
**Pull request by tushar5526**
Context: https://github.com/Mission-Prerna/PrernaLakshyaBackend/issues/72
1. SendOTP - returns the same response as `/api/sendOTP`

```
curl --location --request POST 'http://128.199.28.17:3000/auth/sendOTP?phone=6307422471&errorMessage=Mobile%20number%20could%20not%20be%20verified.%20Please%20get%20in%20touch%20with%20the%20DC%20in%20your%20District%27s%20BSA%20office%20if%20your%20number%20is%20not%20registered%20on%20the%20Prerna%20Portal.' \
--header 'x-application-id: 320b020a-3d84-4d8a-a191-da4e972c2951'
```

2. Verify OTP - returns the same response as `/api/login` when success else failed response of `/api/verifyOTP`

```
curl --location --request POST 'http://128.199.28.17:3000/auth/verifyOTP?phone=6307422471&otp=7465' \
--header 'x-application-id: 320b020a-3d84-4d8a-a191-da4e972c2951'
```

### CODE REVIEW

**Comment by ChakshuGautam** [comment]
Why not do this in user-service and use a gateway to ensure everything is as expected for the frontend @tushar5526?

**Comment by tushar5526** [comment]
> Why not do this in user-service and use a gateway to ensure everything is as expected for the frontend @tushar5526?

I am not aware of any endpoint in user-service that verifies the OTP, logs in the user (via `/api/login`) and returns the JWT token ? -- `sendOTP` and `verifyOTP` endpoints are there.

**Comment by ChakshuGautam** [comment]
Yes. User service is supposed to be built so that it is extended. If possible can we move this code there?

**Comment by tushar5526** [comment]
> Yes. User service is supposed to be built so that it is extended. If possible can we move this code there?

NL uses a default password for all users to log in. I don't think that is how every other product in Samagra will use user service (FID creates a new password and then updates it using FusionAuth API key)

I believe creating a new password everytime user logins via admin API is the right approach, but I don't have complete visibility on the side effects of using this method in NL as NL uses a hardcoded default password for each user. 

I am thinking of making a PR to User Service and other services can use the newer flow - while NL uses the current PR to forward requests, also it would be one less exposed service to manage in NL as user service is exposed only to handle auth ?

**Comment by tushar5526** [comment]
Going ahead with the above approach - to move to the user service's method of random password logins after a month when every Firebase config has synced across all devices.

**Pull request merged**
